version: "3.9"

services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app_network
    command: ["sh", "-c", "yarn prisma generate && yarn prisma migrate deploy && yarn build && yarn start:prod"]

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
