version: "3.9"

services:
  postgres:
    image: postgres:15.3
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    networks:
      - app_network
    profiles:
      - production

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
